on:
  schedule:
    - cron: '* * * * *'

  workflow_dispatch:  # click the button on Github repo!


jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: tiann
          base: KernelSU
          head: main
